config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Mount the mission_control-jobs engine
  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "home#index"
  get "/my_activities", to: "home#index"
  get "/group_activities", to: "home#group_activities", as: :group_activities
  get "/history", to: "home#history", as: :activity_history

  resources :activities, only: [:show, :destroy] do
    resources :tasks, only: [:show] do
      member do
        post :run
      end
    end
  end
  get "/activities/new/:type", to: "activities#new", as: "new_activity_with_type"
  post "/activities", to: "activities#create"

  resources :manifest_registries, only: [:index, :show, :create, :destroy] do
    member do
      post :run
    end
  end
end

app/views/shared/_flash_messages.html.erb
<div class="toast toast-top toast-center" data-controller="autohide" data-autohide-delay-value="5000">
  <% if notice %>
    <div class="alert alert-success">
      <%= icon "check-circle", class: "stroke-current shrink-0 h-6 w-6" %>
      <span><%= notice %></span>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-error">
      <%= icon "x-circle", class: "stroke-current shrink-0 h-6 w-6" %>
      <span><%= alert %></span>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-300">
    <div class="navbar-start">
      <%= image_tag "CollectionSpace-Logo.png", alt: "CollectionSpace Logo", height: 30, class: "inline-block align-top my-2 max-w-48 w-auto" %>
    </div>
    <div class="navbar-end">
      <% if authenticated? %>
        <%= link_to "My profile", user_path(Current.user), class: "btn btn-success btn-outline mr-2" %>
        <%= button_to "Sign Out", session_path, method: :delete, class: "btn btn-secondary btn-outline" %>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_menu.html.erb
<%= render "shared/card/base", card_class: "bg-base-300 shadow-lg" do %>
  <h2 class="card-title mb-4"><%= t("ui.menu.title") %></h2>
  <div class="mb-4">
    <%= render partial: "shared/card/subtitle", locals: { title: t("ui.menu.view.title") } %>
    <ul class="menu w-full">
      <%= render partial: "shared/menu/item",
                 locals: {
                   menu_item_name: t("ui.menu.view.my"),
                   menu_item_icon: "user",
                   menu_item_path: my_activities_path
                 } %>
      <%= render partial: "shared/menu/item",
                 locals: {
                   menu_item_name: t("ui.menu.view.group"),
                   menu_item_icon: "list-bullet",
                   menu_item_path: group_activities_path
                 } %>
      <%= render partial: "shared/menu/item",
                 locals: {
                   menu_item_name: t("ui.menu.view.history"),
                   menu_item_icon: "archive-box",
                   menu_item_path: activity_history_path
                 } %>
    </ul>
  </div>

  <div class="mb-4">
    <%= render partial: "shared/card/subtitle", locals: { title: t("ui.menu.perform.title") } %>
    <ul class="menu w-full">
      <% Activity.activity_type_display_names.each do |name| %>
        <%= render partial: "shared/menu/item",
                   locals: {
                     menu_item_name: name,
                     menu_item_icon: "plus-circle",
                     menu_item_path: new_activity_with_type_path(type: name.parameterize)
                   } %>
      <% end %>
    </ul>
  </div>

  <% if admin? %>
    <div>
      <%= render partial: "shared/card/subtitle", locals: { title: t("ui.menu.admin.title") } %>
      <ul class="menu w-full">
        <%= render partial: "shared/menu/item",
                   locals: {
                     menu_item_name: t("ui.menu.admin.jobs"),
                     menu_item_icon: "chart-bar",
                     menu_item_path: "/jobs"
                   } %>
        <%= render partial: "shared/menu/item",
                   locals: {
                     menu_item_name: t("ui.menu.admin.registries"),
                     menu_item_icon: "document-duplicate",
                     menu_item_path: manifest_registries_path
                   } %>
      </ul>
    </div>
  <% end %>
<% end %>