config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Mount the mission_control-jobs engine
  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "home#index"
  get "/my_activities", to: "home#index"
  get "/group_activities", to: "home#group_activities", as: :group_activities
  get "/history", to: "home#history", as: :activity_history

  resources :activities, only: [:show, :destroy] do
    resources :tasks, only: [:show] do
      member do
        post :run
      end
    end
  end
  get "/activities/new/:type", to: "activities#new", as: "new_activity_with_type"
  post "/activities", to: "activities#create"

  resources :manifest_registries, only: [:index, :show, :create, :destroy] do
    member do
      post :run
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  include ActivityDefinition
  include Advanceable
  include Historical

  # Disable STI - we use "type" column for activity type identifiers
  self.inheritance_column = :_type_disabled

  belongs_to :data_config
  belongs_to :user
  has_many :data_items, dependent: :destroy
  has_many :tasks # dependent: :destroy handled in Historical concern
  has_many_attached :files, dependent: :destroy
  has_one :batch_config, dependent: :destroy
  accepts_nested_attributes_for :batch_config

  validates :batch_config, presence: true, if: -> { has_batch_config? }
  validates :label, presence: true, length: {minimum: 3}
  validate :is_eligible?

  after_initialize :set_config_defaults, if: :new_record?
  after_create_commit do
    workflow.each do |task|
      tasks.create(type: task)
    end
  end

  broadcasts_refreshes

  def current_task
    tasks.where.not(progress_status: Task::PENDING).order(:created_at).last
  end

  def done?
    last_task? && current_task.outcome_succeeded?
  end

  def last_task?
    current_task == tasks.last
  end

  def next_task
    tasks.where(progress_status: Task::PENDING).order(:created_at).first
  end

  # Activity type definitions
  activity_type :check_media_derivatives do |a|
    a.display_name = "Check Media Derivatives"
    a.file_requirement = :one_or_more
    a.has_batch_config = false
    a.has_config_fields = false
    a.workflow = [:process_uploaded_files, :pre_check_ingest_data, :process_media_derivatives]
    a.data_config_type = "media_record_type"
    a.data_handler = ->(activity) { CollectionSpaceMapper.single_record_type_handler_for(activity) }
  end

  activity_type :create_or_update_records do |a|
    a.display_name = "Create or Update Records"
    a.file_requirement = :one
    a.has_batch_config = true
    a.has_config_fields = true
    a.workflow = [:process_uploaded_files, :pre_check_ingest_data]
    a.data_config_type = "record_type"
    a.data_handler = ->(activity) { CollectionSpaceMapper.single_record_type_handler_for(activity) }
    a.config_defaults = {action: "create"}
    a.validations = ->(record) {
      record.errors.add(:config, "can't be blank") if record.config.blank?
    }
  end

  activity_type :delete_records do |a|
    a.display_name = "Delete Records"
    a.file_requirement = :one
    a.has_batch_config = true
    a.has_config_fields = false
    a.workflow = [:process_uploaded_files]
    a.data_config_type = "record_type"
    a.select_attributes = [] # TODO: [:record_matchpoint]
  end

  activity_type :export_record_ids do |a|
    a.display_name = "Export Record IDs"
    a.file_requirement = :none
    a.has_batch_config = false
    a.has_config_fields = false
    a.workflow = []
    a.data_config_type = "record_type"
  end

  activity_type :import_terms do |a|
    a.display_name = "Import Terms"
    a.file_requirement = :one
    a.has_batch_config = false
    a.has_config_fields = false
    a.workflow = []
    a.data_config_type = "term_list"
  end

  private

  def is_eligible?
    return unless user
    return unless activity_type

    if DataConfig.for(user, self).empty?
      errors.add(:data_config, "is not eligible for this activity")
    end
  end

  def set_config_defaults
    defaults = {auto_advance: true}
    if activity_config&.config_defaults
      defaults = defaults.merge(activity_config.config_defaults)
    end
    self.config = defaults.merge((config || {}).symbolize_keys)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :destroy]
  before_action :verify_activity_type, only: [:new]

  def new
    @activity = Activity.new(type: @activity_type)
    @activity.build_batch_config if @activity.has_batch_config?
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = Current.user

    if @activity.save
      redirect_to activity_path(@activity), notice: "#{@activity.display_name} was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  def show
  end

  def destroy
    @activity.destroy
    redirect_to root_path, status: :see_other, notice: "Activity was successfully deleted."
  end

  private

  def set_activity
    accessible_activities = Activity.includes(:user, :data_config, :batch_config, :tasks)
      .joins(:user)
      .where(users: {cspace_url: Current.collectionspace})

    @activity = accessible_activities.find_by(id: params[:id])

    unless @activity
      redirect_to my_activities_url, alert: "You don't have permission to access this activity."
    end
  end

  def verify_activity_type
    @activity_type = Activity.find_activity_type_by_param_name(params[:type])

    unless @activity_type
      redirect_to my_activities_url, flash: {alert: "Invalid activity type"}
    end
  end

  def activity_params
    base_params = [
      :type,
      :label,
      :data_config_id,
      {files: []},
      config: {},
      batch_config_attributes: BatchConfig.boolean_attributes + BatchConfig.select_attributes
    ]

    params.require(:activity).permit(base_params)
  end
end

app/views/activities/_activity.html.erb
<%= turbo_stream_from activity %>
<%= render "shared/card/base", id: dom_id(activity), card_class: "bg-base-100 shadow-md mb-3" do %>
  <div class="card-title justify-between">
    <%= link_to activity_path(activity), class: "link link-info" do %>
      <%= render partial: "shared/card/title",
                 locals: { title: activity.label } %>
    <% end %>
    <div class="card-actions">
      <% if activity.user == Current.user %>
        <%= link_to activity_path(activity), class: "btn btn-error btn-sm", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this activity?" }, title: "Delete activity" do %>
          <%= icon "trash", class: "size-3" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if activity.user != Current.user %>
    <div class="text-right text-sm opacity-70 -mt-2 mb-4">
      <%= activity.user.email_address %>
    </div>
  <% end %>

  <%= render "shared/card/property_grid", columns: 2 do %>
    <%= render partial: "shared/card/item",
               locals: { property: "Activity Type", value: activity.display_name } %>

    <%= render partial: "shared/card/item",
               locals: { property: data_config_type_label(activity), value: activity.data_config.display_name } %>

    <%= render partial: "shared/card/item",
               locals: {
                 property: "Workflow Task",
                 value: capture do %>
                   <% if activity.current_task %>
                     <span class="font-mono font-medium mr-2"><%= task_name(activity) %></span>
                     <%= format_task_status_badge(activity.current_task.status) %>
                   <% else %>
                     <span class="font-mono font-medium">No task is active</span>
                   <% end %>
                 <% end
               } %>

    <%= render partial: "shared/card/item",
               locals: { property: "Last Updated", value: local_time(activity.updated_at) } %>
  <% end %>
<% end %>

app/views/activities/_activity_config.html.erb
<div class="mb-6">
  <%= render partial: "shared/card/subtitle", locals: { title: "Activity Config" } %>

  <div>
    <% @activity.config.each do |key, value| %>
      <span class="badge badge-neutral mr-2 mb-2">
        <%= key.to_s.humanize %>:
        <% if value.is_a?(TrueClass) %>
          <span class="text-success">Yes</span>
        <% elsif value.is_a?(FalseClass) %>
          <span class="text-base-content/60">No</span>
        <% elsif value.nil? %>
          <span class="text-base-content/60 italic">Not set</span>
        <% else %>
          <strong><%= value.to_s %></strong>
        <% end %>
      </span>
    <% end %>
  </div>
</div>

app/views/activities/_batch_config.html.erb
<div class="mb-6">
  <%= render partial: "shared/card/subtitle", locals: { title: "Batch Config" } %>
  <div class="collapse collapse-arrow">
    <input type="checkbox">
    <div class="collapse-title text-sm font-medium">
      Show/Hide
    </div>
    <div class="collapse-content">
      <%= render "shared/card/property_grid", columns: 2 do %>
        <!-- Select field values column -->
        <div>
          <h4 class="font-medium mb-3">Selection Options</h4>

          <%= render "shared/card/property_grid", columns: 2 do %>
            <% BatchConfig.select_attributes.each do |attr_name| %>
              <div class="text-base-content/60"><%= attr_name.to_s.humanize %></div>
              <div class="font-medium"><%= activity.batch_config.send(attr_name) %></div>
            <% end %>
          <% end %>
        </div>

        <!-- Boolean field values column -->
        <div>
          <h4 class="font-medium mb-3">Toggle Options</h4>

          <%= render "shared/card/property_grid", columns: 2 do %>
            <% BatchConfig.boolean_attributes.each do |attr_name| %>
              <div class="text-base-content/60"><%= attr_name.to_s.humanize %></div>
              <div>
                <% if activity.batch_config.send(attr_name) %>
                  <span class="badge badge-success">Enabled</span>
                <% else %>
                  <span class="badge badge-neutral">Disabled</span>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/_batch_config_form.html.erb
<%= form.fields_for :batch_config do |batch_form| %>
  <%= render "shared/card/property_grid", columns: 2 do %>
    <!-- Select fields column -->
    <div>
      <h4 class="font-medium mb-3">Selection Options</h4>

      <% if activity.select_attributes.any? %>
        <%= render "shared/card/property_grid", columns: 2 do %>
          <% activity.select_attributes.each do |attr_name| %>
            <%= batch_form.label attr_name, class: "label-text font-medium" %>
            <div class="form-control">
              <%= batch_form.select attr_name,
                                    options_for_select(
                                      BatchConfig.values(attr_name),
                                      BatchConfig.default_value(attr_name)
                                    ),
                                    { include_blank: "Select option" },
                                    class: "select select-bordered w-full" %>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="mb-4">
          <span class="label-text font-medium">No options to select</span>
        </div>
      <% end %>
    </div>

    <!-- Boolean fields column -->
    <div>
      <h4 class="font-medium mb-3">Toggle Options</h4>

      <%= render "shared/card/property_grid", columns: 2 do %>
        <% activity.boolean_attributes.each do |attr_name| %>
          <%= batch_form.label attr_name, class: "label-text font-medium" %>
          <div class="form-control">
            <%= batch_form.check_box attr_name, class: "toggle toggle-primary" %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/activities/_create_or_update_records_fields.html.erb
<div class="mb-6">
  <%= form.fields_for :config do |config_form| %>
    <div class="mb-4">
      <h4 class="font-medium mb-3">Transfer mode</h4>
      <div class="flex flex-wrap gap-4">
        <div class="form-control">
          <label class="label cursor-pointer">
            <%= config_form.radio_button :action, "create", class: "radio radio-primary",
                                         checked: config_checked?(activity, "action", "create", true) %>
            <span class="label-text ml-2">Create</span>
          </label>
        </div>

        <div class="form-control">
          <label class="label cursor-pointer">
            <%= config_form.radio_button :action, "update", class: "radio radio-primary",
                                         checked: config_checked?(activity, "action", "update") %>
            <span class="label-text ml-2">Update</span>
          </label>
        </div>

        <div class="form-control">
          <label class="label cursor-pointer">
            <%= config_form.radio_button :action, "create_and_update", class: "radio radio-primary",
                                         checked: config_checked?(activity, "action", "create_and_update") %>
            <span class="label-text ml-2">Create and Update</span>
          </label>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity, scope: :activity, url: activities_path, local: true) do |form| %>
  <%= render "shared/card/base", card_class: "bg-base-300 shadow-lg" do %>
    <% actions_content = capture do %>
      <%= form.submit "Submit", class: "btn btn-primary btn-sm" %>
      <%= link_to "Cancel", :back, class: "btn btn-secondary btn-outline btn-sm" %>
    <% end %>
    <%= render "shared/card/header",
               title: "New #{activity.display_name}",
               actions: actions_content %>

    <% if activity.errors.any? %>
      <div class="alert alert-error mb-4">
        <div>
          <h3 class="font-semibold"><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h3>
          <ul class="list-disc list-inside mt-2">
            <% activity.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="mb-6">
      <%= render partial: "shared/card/subtitle", locals: { title: "Basic Information" } %>
      <%= form.hidden_field :type %>

      <%= render "shared/card/property_grid" do %>
        <%= form.label :label, "Label", class: "label-text font-medium" %>
        <div class="sm:col-span-3">
          <%= form.text_field :label,
                               required: true,
                               placeholder: "Enter a reference label i.e. record-batch1",
                               class: "input input-bordered w-full" %>
        </div>

        <%= form.label :data_config, data_config_type_label(activity), class: "label-text font-medium" %>
        <div class="sm:col-span-3">
          <%= form.collection_select :data_config_id, DataConfig.for(Current.user, activity), :id, :display_name,
                                     { include_blank: "Select a #{data_config_type_label(activity)}" },
                                     class: "select select-bordered w-full" %>
        </div>

        <% if activity.file_requirement != :none %>
          <%= form.label :files, activity.file_requirement == :one ? "File" : "Files", class: "label-text font-medium" %>
          <div class="sm:col-span-3">
            <%= form.file_field :files,
                                multiple: activity.file_requirement == :one_or_more,
                                name: "activity[files][]",
                                class: "file-input file-input-bordered w-full" %>
          </div>
        <% end %>
      <% end %>
    </div>

    <% if activity.has_config_fields? %>
      <%= render "#{activity.display_name.parameterize(separator: "_")}_fields", form: form, activity: activity %>
    <% end %>

    <% if activity.has_batch_config? %>
      <div class="mb-6">
        <%= render partial: "shared/card/subtitle", locals: { title: "Batch config" } %>
        <%= render "batch_config_form", form: form, activity: activity %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/activities/new.html.erb
<%= render "form", activity: @activity %>

app/views/activities/show.html.erb
<%= turbo_stream_from @activity %>

<%= render "shared/card/base", card_class: "bg-base-300 shadow-lg mb-6" do %>
  <div id="<%= dom_id(@activity) %>">
    <% actions_content = capture do %>
      <% if @activity.user == Current.user %>
        <%= button_to activity_path(@activity),
                      method: :delete,
                      data: { turbo_confirm: "Are you sure you want to delete this activity?" },
                      form_class: "inline",
                      class: "btn btn-error btn-sm" do %>
          <%= icon "trash", class: "size-3" %>
        <% end %>
      <% end %>
    <% end %>
    <%= render "shared/card/header",
               title: @activity.display_name,
               actions: actions_content %>

    <div class="mb-6">
      <%= render partial: "shared/card/subtitle", locals: { title: "Basic Information" } %>

      <%= render "shared/card/property_grid" do %>
        <%= render partial: "shared/card/info",
                   locals: { property: "Label", value: @activity.label } %>
        <%= render partial: "shared/card/info",
                   locals: {
                     property: data_config_type_label(@activity),
                     value: @activity.data_config.display_name
                   } %>
        <% if @activity.files.attached? %>
          <%= render partial: "shared/card/info",
                     locals: {
                       property: "Attached Files",
                       value: format_attached_files(@activity.files)
                     } %>
        <% end %>
        <%= render partial: "shared/card/info",
                    locals: { property: "Total Rows", value: @activity.data_items_count } %>
        <%= render partial: "shared/card/info",
                   locals: { property: "Created By", value: @activity.user.email_address } %>
        <%= render partial: "shared/card/info",
                   locals: { property: "Created On", value: local_time(@activity.created_at) } %>
      <% end %>
    </div>

    <% if @activity.config.any? %>
      <%= render partial: "activity_config", locals: { activity: @activity } %>
    <% end %>

    <% if @activity.batch_config.present? %>
      <%= render partial: "batch_config", locals: { activity: @activity } %>
    <% end %>
  </div>
<% end %>

<%= render "shared/card/base",
           card_class: "bg-base-300 shadow-lg" do %>
  <h2 class="card-title mb-4">Workflow Tasks</h2>
  <div class="overflow-x-auto">
    <table class="table table-hover bg-base-100">
      <thead>
      <tr>
        <th>Task</th>
        <th>Status</th>
        <th>Created</th>
        <th>Updated</th>
        <th></th>
      </tr>
      </thead>
      <tbody id="activity_<%= @activity.id %>_tasks">
      <%= render partial: "tasks/task", collection: @activity.tasks.order(:created_at) %>
      </tbody>
    </table>
  </div>
<% end %>